version: '3.8'

services:
    ### DATABASE ###
    postgres:
        container_name: postgres
        image: postgres:latest
        restart: on-failure
        ports:
            - 5432:5432
        volumes:
            - dbdata:/data/postgres
        networks: 
            - database
        env_file:
            - .env
    
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:4.29
        restart: always
        depends_on:
            - postgres
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        volumes:
            - pgdata:/root/.pgadmin
        ports:
            - "${PGADMIN_PORT}:80"
        networks: 
            - database
            
    ### BACKEND ###
    # gw-pool:
    #     container_name: gw-pool
    #     image: hectormrc/gw-pool:alpha
    #     restart: always
    #     ports:
    #         - "8080:${SERVICE_PORT}"
    #     networks: 
    #         - database
    #     env_file:
    #         - .env

networks:
    ## Database network is the bridge between domain environment and the sql databases
    database:
        name: database
        driver: bridge

volumes:
    dbdata:
    pgdata: